// Generated by scripts/edge_generate_types.py; do not hand edit.
export type Capabilities = { "api_version"?: "1"; "core_version"?: "0.2.0"; "drivers": (string)[]; "edge_version"?: "0.1.0"; "protocol"?: 3; "provider": string; "qualification_refs": (string)[]; "runtime_mode": "appliance" | "interactive" | "replay" };
export type Clock = { "domain": "edge_monotonic"; "emitted_ms": number; "valid_for_ms": number };
export type Error = { "api_version"?: "1"; "error": "invalid_request" | "unauthorized" | "forbidden" | "capacity" | "source_unavailable" | "not_found"; "retryable"?: boolean };
export type HealthEvent = { "api_version"?: "1"; "kind": "health" | "gap"; "reason": "source_lost" | "clock_untrusted" | "calibration_expired" | "model_error" | "overload" | "stream_gap" | "closed"; "retryable": boolean; "scene_state"?: "UNKNOWN"; "sequence": number; "session": string };
export type Prediction = { "centre": (number)[]; "evidence": false; "horizon_ms": 200 };
export type Recommendation = { "action": "WARN" | "STOP" | "HOVER" | "LAND" | "RETREAT"; "contract": "warn" | "vehicle_stop" | "drone_hover" | "drone_land" | "drone_retreat"; "reason": "hazard_or_unknown" | "observe"; "requires_independent_controller": true };
export type ReplayReport = { "api_version": "1"; "frame_count": number; "results": (V3Snapshot)[]; "runtime_mode": "replay" };
export type SceneEnvelope = { "api_version"?: "1"; "clock": Clock; "kind"?: "scene"; "result": V3Snapshot; "sequence": number; "session": string };
export type SessionHandle = { "session": string; "source_profile": string };
export type SessionRequest = { "contract": "warn" | "vehicle_stop" | "drone_hover" | "drone_land" | "drone_retreat"; "source_profile": string };
export type Track = { "box": (number)[]; "class": "person" | "cyclist" | "vehicle" | "uav" | "animal" | "obstacle" | "equipment" | "hot" | "cold" | "fire_like" | "smoke"; "covariance": (number)[]; "direction_rad": number | null; "expires_at_ms": number; "freshness_ms": number; "id": string; "prediction": Prediction | null; "range_m": number | null; "score": number; "score_semantics": "uncalibrated_support"; "sources": ("rgb" | "lwir" | "radar" | "depth" | "nir")[]; "state": "tentative" | "observed" | "coasting"; "status": "PRESENT" | "UNKNOWN"; "velocity_normalized_per_s": (number)[] | null };
export type V3Snapshot = { "at_ms": number; "evidence": "synthetic" | "recorded" | "external_unverified" | null; "expires_at_ms": number; "reasons": (string)[]; "recommendation": Recommendation; "state": "PRESENT" | "UNKNOWN"; "tracks": (Track)[]; "version": 3 };
