"""Deterministic TypeScript declarations and runtime JSON Schema from OpenAPI."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def type_of(schema):
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(x) for x in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(type_of(x) for x in schema["anyOf"])
    kind = schema.get("type")
    if kind == "array":
        return "(" + type_of(schema["items"]) + ")[]"
    if kind == "object":
        return (
            "{ "
            + "; ".join(
                json.dumps(k) + ("" if k in schema.get("required", []) else "?") + ": " + type_of(v)
                for k, v in schema.get("properties", {}).items()
            )
            + " }"
        )
    return {
        "string": "string",
        "number": "number",
        "integer": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(kind, "never")


def run():
    spec = json.loads((ROOT / "contracts/openapi/aethron-edge-v1.json").read_text())
    schemas = spec["components"]["schemas"]
    output = ROOT / "examples/clients/typescript/src"
    (output / "types.ts").write_text(
        "// Generated by scripts/edge_generate_types.py; do not hand edit.\n"
        + "\n".join(
            "export type " + name + " = " + type_of(schema) + ";"
            for name, schema in schemas.items()
        )
        + "\n"
    )
    bundle = {"$ref": "#/$defs/SceneEnvelope", "$defs": schemas}
    (output / "scene.schema.json").write_text(
        json.dumps(bundle, sort_keys=True, indent=2).replace("#/components/schemas/", "#/$defs/")
        + "\n"
    )


if __name__ == "__main__":
    run()
